version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: imad

  rabbit:
    image: rabbitmq:3.8-management
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  authservice:
    image: imadelfetouh99/authservice:latest
    container_name: authservice
    restart: always
    ports:
      - "8081:8080"
    environment:
      AUTHSERVICE_MYSQL_MASTER_HOST: mysql
      AUTHSERVICE_MYSQL_REPLICA_HOST: mysql
      AUTHSERVICE_MYSQL_MASTER_PORT: 3306
      AUTHSERVICE_MYSQL_REPLICA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: imad
      RABBIT_HOST: rabbit
      secretkey: secretkeyforkwetterimadinjwt@semester6